apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
      - name: hello-world-app
        image: carolledevops/helloworld:v1
        ports:
        - containerPort: 5000
     
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-app
    k8s-app: hello-world-app
    name: hello-world-app
spec:
 ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
 type: LoadBalancer
 selector:
    app: hello-world-app
