apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
      - name: hello-world-app
        image: carolledevops/helloworld:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
     
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-app
    k8s-app: hello-world-app
    name: hello-world-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8081
  type: LoadBalancer
  selector:
    app: hello-world-app