pipeline {
     environment {
       IMAGE_NAME = "my-python-app"
       IMAGE_TAG = "1.0.1"
       CONTAINER_PORT = "8081"
       HOST_PORT = "80"
     }
     agent none
     stages {

         stage('Build image') {
             agent any
             steps {
                script {
                  cd cd Helloworld/code-application
                  sh 'docker build -t edennolan2021/$IMAGE_NAME:$IMAGE_TAG .'
                }
             }
        }
        stage('login to docker') {

	      steps {
	        script {
	          withCredentials([
	            string(credentialsId: 'dockerhub', variable: 'PASSWORD')
	          ]) {

	            sh '''
                    docker login  -u dockerhub -p $PASSWORD
	            '''
	          }

	        }

	      }

	    }
 }
}
    
      
      