project         = "helloworld-391505"
region          = "us-west1"
zone            = "us-west1-a"
machine_type    = "n1-standard-1"
jenkins_address = "jenkins"
sonar_address   = "sonar"
instance_name   = ["jenkins", "sonarqube"]
image           = ["helloworld-391505/jenkins", "centos-cloud/centos-7"]
subnet_name     = "hello-subnet"
vpc_name        = "hello-network"
